version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild

builds:
  - builder: rust
    binary: argocd-lint
    targets:
      - x86_64-unknown-linux-musl
      - x86_64-unknown-linux-gnu
    flags:
      - --release
      - --default-features=false
      - --features=console